### ISSUE TITLE
bodyNoSig  was not set in a response although the flag is on.

### ISSUE THREAD

**Issue by itarinka** [dekelcohen/email-signature-detector#3]
I call the follow code:

const body = 'Stam text';
const email = ;dekel@mail.com';
const displayName = 'Dekel Cohen';
const ret = signature.getSignature(body, {email, displayName}, true);

The received response is {signature: '', found: false}, there is no "bodyNoSig" field.

**Comment by dekelcohen** [comment]
It is always advisable to check for found flag (meaning a sig was found).
Anyway, added default empty bodyNoSig = ''

**Comment by dekelcohen** [comment]
Reverted this fix. As documented bodyNoSig is only set if requested and signature is found
