### ISSUE TITLE
Signature not removed for a specific email

### ISSUE THREAD

**Issue by itarinka** [dekelcohen/email-signature-detector#5]
Signature not removed for the follow code:

const body = 'Test complex signature.\n' +
            'Dekel Cohen\n' +
            'IBM (Telelogic AB) Southern California Edison Company\n' +
            '1111 Farmington Avenue, Farmington, CT 11111-XXXX Office: 111.679.XXXX | Cell: 111.679.XXXX | Fax: 111.679.XXXXwww.att.com';
const email = 'dekel@mail.com';
const displayName = 'Dekel Cohen';
const ret = signature.removeSignature(body, {email, displayName});

**Comment by dekelcohen** [comment]
Cannot reproduce. 
This is the (correct) output when tested the above code:
"Test complex signature."
Are you using the latest in development branch (npm update may be necessary) ?

**Comment by itarinka** [comment]
Now I updated the text of the email.  Please try again.

**Comment by dekelcohen** [comment]
Working on a solution
