### ISSUE TITLE
removeSignature got stuck on a specific email.

### ISSUE THREAD

**Issue by itarinka** [dekelcohen/email-signature-detector#6]
const textForTermsExtraction = 'second, third and forth msg attachment. la la la la la   goodbye. \n' +
            ' \n' +
            '            Yaarit David Calendar\n' +
            ' yaaritd@harmon.ie\n' +
            ' Wednesday, November 4, 2015 – Tuesday, November 10, 2015\n' +
            ' Time zone: (UTC+02:00) Jerusalem\n' +
            ' (Adjusted for Daylight Saving Time)               November 2015         Su   Mo   Tu   We   Th   Fr   Sa                  1    2    3    4   5   6   7             8   9   10   11    12    13    14              15    16    17    18    19    20    21              22    23    24    25    26    27    28              29    30                                                 Busy      Tentative      Free        Out of Office      Working Elsewhere      Outside of Working Hours                  November 2015               Wed, Nov 4                Before 8:00 AM    Outside of Working Hours         8:00 AM – 11:30 AM    Free         11:30 AM – 11:45 AM    Tentative         11:45 AM – 3:30 PM    Free         3:30 PM – 4:00 PM    Busy         4:00 PM – 5:00 PM    Free         After 5:00 PM    Outside of Working Hours               Thu, Nov 5                Before 8:00 AM    Outside of Working Hours         8:00 AM – 11:30 AM    Free         11:30 AM – 11:45 AM    Tentative         11:45 AM – 12:30 PM    Free         12:30 PM – 1:30 PM    Busy         1:30 PM – 5:00 PM    Free         After 5:00 PM    Outside of Working Hours               Fri, Nov 6                Before 8:00 AM    Outside of Working Hours         8:00 AM – 5:00 PM    Free         After 5:00 PM    Outside of Working Hours               Sat, Nov 7 – Sun, Nov 8                 All Day     Outside of Working Hours               Mon, Nov 9 – Tue, Nov 10                 Before 8:00 AM    Outside of Working Hours         8:00 AM – 11:30 AM    Free         11:30 AM – 11:45 AM    Tentative         11:45 AM – 5:00 PM    Free         After 5:00 PM    Outside of Working Hours';
        const from = {
            displayName: 'Yaarit David',
            mail: 'yaaritd@harmon.ie',
            personType: 'contact',
            systemName: 'mail',
        };
        const mail = {
            from,
            body: textForTermsExtraction,
        };
        const text = textProcessor.removeSignature(mail);

**Comment by dekelcohen** [comment]
Fixed https://github.com/dekelcohen/email-signature-detector/commit/01ec293224dfcd4a745452e4828d7e0a320b5e0a
